### ISSUE TITLE
Duda de como generar el tablero

### ISSUE THREAD

**Issue by facundofabbi** [facundofabbi/EntregaFinal#2]
Hola profe tenemos una consulta sobre como hacer el tablero. La primera idea fue hacerlo como esta subido ahora en guit pero nos dimos cuenta que si queríamos ponerle identificadores (doble , triple o restar) a los botones no se podía por lo q pensamos configurar botón por botón , eso estaría correcto?
@tomibarbieri

**Comment by tomibarbieri** [comment]
Hola Facundo, consulta sobre esto.. ya lo solucionaron, como lo pensaron ?

**Comment by facundofabbi** [comment]
Profe ya esta todo mas encaminado el jueves le mostramos como venimos
Muchas gracias ! saludos grupo 10
